branches:
  only:
  - master

sudo: true

language: cpp


matrix:
  include:
    - os: osx
      osx_image: xcode10.1


before_install:
  - git config branch.autosetupmerge always && git config branch.autosetuprebase always
  - export PATH=$PATH:$(pwd)/depot_tools/



install:
  - fetch --nohooks webrtc
  - sed -i -e "s|'src/resources'],|'src/resources'],'condition':'rtc_include_tests==true',|" src/DEPS
  - gclient sync
  - cd ./src
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then gn gen out/macos --args="is_debug=false target_cpu=\"x64\" rtc_include_tests=false"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ninja webrtc -C out/macos; fi
  - mkdir out/macos/release && mkdir out/macos/release/include && cp out/macos/obj/libwebrtc.a out/macos/release/ && find -name "*.h" | xargs cp --parents -t ./out/macos/release/include/



script:
  - echo "webrtc"




deploy:
  provider: releases
  api_key: dd389876208fbe846369a668b164063f909d8792
  file_glob: true
  file: src/out/macos/release/*
  skip_cleanup: true
  draft: true