branches:
  only:
  - master

sudo: true

language: c++


matrix:
  include:
    - os: osx
      osx_image: xcode10.1


before_install:
  - git config branch.autosetupmerge always && git config branch.autosetuprebase always
  - export PATH=$PATH:$(pwd)/depot_tools/



install:
  - fetch --nohooks webrtc
  - sed -i -e "s|'src/resources'],|'src/resources'],'condition':'rtc_include_tests==true',|" src/DEPS
  - gclient sync
  - gn gen out/Default --args="is_debug=false target_cpu=\"x64\" rtc_include_tests=false"
  - ninja -C out/Default


script:
  - echo "webrtc"
