branches:
  only:
  - master
sudo: true
language: cpp



env:
  global:
  - RELEASE_TO_GITHUB="yes"





matrix:
  include:
  - os: osx
    osx_image: xcode10.1
    env: TARGET_OS=ios
  - os: osx
    osx_image: xcode10.1
    env: TARGET_OS=osx
  - os: linux
    dist: xenial
    env: TARGET_OS=android
  - os: linux
    dist: xenial
    env: TARGET_OS=linux



before_install:
  - git config branch.autosetupmerge always && git config branch.autosetuprebase always
  - export PATH=$PATH:$(pwd)/depot_tools/
  - export SRC_DIR=$(pwd)/src
  - export ROOT_DIR=$(pwd)
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install git-lfs; fi


install:
  - if [ "$TARGET_OS" == "ios" ]; then bash build_ios.sh; fi 
  - if [ "$TARGET_OS" == "osx" ]; then bash build_mac.sh; fi
  - if [ "$TARGET_OS" == "android" ]; then bash build_android.sh; fi
  - if [ "$TARGET_OS" == "linux" ]; then bash build_linux.sh; fi
  

script:
  - echo "webrtc"


